server:
  port: 8090

# properties for database connection
spring:
  application:
    hostname: localhost
  datasource:
    url: jdbc:mysql://${spring.application.hostname}:3306/online_banking_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Registration in service discovery
eureka:
  client:
    service-url:
      defaultzone: http://${spring.application.hostname}:8761/eureka
