server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
# Location for all services properties resources/configurations
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations